### ISSUE TITLE
The context attention question

### ISSUE THREAD

**Issue by DingYunxia** [tuhinjubcse/ALW3-ACL2019#1]
Hi，author
I‘m now trying to use your model of context attention（AttLayer）. When I tried to add it to my model, it can be compile but not fit. 
This is my model:
    inputs = Input(shape=(MAX_SENTENCE_LENGTH, ), dtype='int32')
    embedding = Embedding(len(word_index)+1, 
                          EMBEDDING_DIM, 
                          weights=[embedding_weights])(inputs) 
    x = Bidirectional(LSTM(256, recurrent_dropout=0.35, return_sequences=True))(embedding)

    att = AttLayer()(x) 
    output = Dense(2, activation='softmax')(att)
    model = Model(inputs=inputs, outputs=output)
    model.compile(loss='binary_crossentropy',
                  optimizer='adam',
                  metrics=['accuracy'])
    model.summary()

model.fit(train_pad_data, labels,
          batch_size=128,
          epochs= 10,
          callbacks=[early_stopping],
          validation_data=(dev_pad_data, dev_labels))

The error message is as follows：
Train on 9000 samples, validate on 1000 samples
Epoch 1/10
Traceback (most recent call last):

  File "<ipython-input-134-b33fc818aa91>", line 5, in <module>
    validation_data=(dev_pad_data, dev_labels))

  File "D:\Anaconda3\lib\site-packages\keras\engine\training.py", line 1039, in fit
    validation_steps=validation_steps)

  File "D:\Anaconda3\lib\site-packages\keras\engine\training_arrays.py", line 199, in fit_loop
    outs = f(ins_batch)

  File "D:\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)

  File "D:\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)

  File "D:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1439, in __call__
    run_metadata_ptr)

  File "D:\Anaconda3\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))

InvalidArgumentError: Input to reshape is a tensor with 5760 values, but the requested shape requires a multiple of 512
	 [[{{node attention1_23/Reshape_3}}]]

I don't know how to solve this problem, I hope you can help me. 
Thank you.

**Comment by tuhinjubcse** [comment]
use KERAS_BACKEND=theano and python2 ? 
hope that helps

**Comment by DingYunxia** [comment]
we use keras_backend=tensor flow and python 3.6  

But we use your code “Attention class” it‘s ok！It can be compile and fit. So I don't think it has anything to do with keras_backend.

    
        
            
                
                    
                        
                    
                    
                        
                            丁云霞
                            
                            
                                
                                    邮箱：1164840664@qq.com
                                
                        
                    
                
            
        
    
签名由 网易邮箱大师 定制
On 08/18/2019 22:29, Tuhin Chakrabarty wrote: use KERAS_BACKEND=theano and python2 ?
hope that helps

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/tuhinjubcse/ALW3-ACL2019/issues/1?email_source=notifications\u0026email_token=AHV6H3WDFWH6MRNFU66SRS3QFFMENA5CNFSM4IMTE7T2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD4RBGQY#issuecomment-522326851",
"url": "https://github.com/tuhinjubcse/ALW3-ACL2019/issues/1?email_source=notifications\u0026email_token=AHV6H3WDFWH6MRNFU66SRS3QFFMENA5CNFSM4IMTE7T2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD4RBGQY#issuecomment-522326851",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by tuhinjubcse** [comment]
Try python 2 , I really dont understand much from ur error

**Comment by DingYunxia** [comment]
OK，thank you、I will try it.

    
        
            
                
                    
                        
                    
                    
                        
                            丁云霞
                            
                            
                                
                                    邮箱：1164840664@qq.com
                                
                        
                    
                
            
        
    
签名由 网易邮箱大师 定制
On 08/18/2019 23:00, Tuhin Chakrabarty wrote: Try python 2 , I really dont understand much from ur error

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/tuhinjubcse/ALW3-ACL2019/issues/1?email_source=notifications\u0026email_token=AHV6H3QKWSEG4X5ZMEDE3BLQFFPY3A5CNFSM4IMTE7T2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD4RBYXY#issuecomment-522329183",
"url": "https://github.com/tuhinjubcse/ALW3-ACL2019/issues/1?email_source=notifications\u0026email_token=AHV6H3QKWSEG4X5ZMEDE3BLQFFPY3A5CNFSM4IMTE7T2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD4RBYXY#issuecomment-522329183",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
